runtime: nodejs14

handlers:
  - url: /api/.*
    script: auto

  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: static/\1
    upload: static/(.*\..+)$

  # Catch all handler to index.html
  - url: /.*
    static_files: static/index.html
    upload: static/index.html

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10